version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    restart: always

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: always
